name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 가져오기
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Corepack 활성화
        run: corepack enable

      - name: package.json에서 버전 추출
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 의존성 캐싱
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}

      - name: 의존성 설치
        run: pnpm install

      - name: 프로젝트 빌드
        run: pnpm build

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        env:
          REPO_NAME: ${{ vars.DOCKER_HUB_USERNAME }}/nextjs-deploy-playground
          IMAGE_TAG: ${{ steps.package-version.outputs.current-version }}
        run: |
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest" # 태그가 비어있다면 latest로 설정
          fi

          echo "Using image tag: $IMAGE_TAG"

          docker build -t $REPO_NAME:$IMAGE_TAG .next/standalone/* .next/static/* public/*
          docker tag $REPO_NAME:$IMAGE_TAG $REPO_NAME:latest # 버전 태그 및 Latest 태그를 추가

          docker push $REPO_NAME:$IMAGE_TAG
          docker push $REPO_NAME:latest
