name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 가져오기
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Corepack 활성화
        run: corepack enable

      - name: package.json에서 버전 추출
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 의존성 캐싱
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}

      - name: 의존성 설치
        run: pnpm install

      - name: .env 파일 선택
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            ENV_FILE=".env.prod"
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            ENV_FILE=".env.staging"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            ENV_FILE=".env.dev"
          fi

          if [ -n "$ENV_FILE" ]; then
            echo "사용할 .env 파일: $ENV_FILE"
            cp $ENV_FILE .env
          else
            echo "ENV_FILE이 지정되지 않았습니다. 기본 환경 설정을 사용합니다."
          fi

      - name: 프로젝트 빌드
        run: pnpm build

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        env:
          REPO_NAME: ${{ vars.DOCKER_HUB_USERNAME }}/nextjs-deploy-playground
          IMAGE_TAG: ${{ steps.package-version.outputs.current-version }}
        run: |
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest" # 태그가 비어있다면 latest로 설정
          fi

          echo "Using image tag: $IMAGE_TAG"

          docker build \
            --build-arg DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }} \
            --build-arg DATADOG_VERSION=${{ steps.package-version.outputs.current-version }} \
            --build-arg DATADOG_SERVICE=my-nextjs-playground \
            --build-arg DATADOG_PREFIX=https://bearcookiestudy.shop \
            -t $REPO_NAME:$IMAGE_TAG .
          docker tag $REPO_NAME:$IMAGE_TAG $REPO_NAME:latest # 버전 태그 및 Latest 태그를 추가

          docker push $REPO_NAME:$IMAGE_TAG
          docker push $REPO_NAME:latest

      - name: AWS EC2에 SSH 연결 및 Docker 컨테이너 업데이트 후 재시작
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          port: ${{ vars.EC2_SSH_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ vars.DOCKER_HUB_USERNAME }}/nextjs-deploy-playground:latest
            sudo docker stop nextjs-deploy-playground || true
            sudo docker rm nextjs-deploy-playground || true
            sudo docker run -d -p 3000:3000 --name nextjs-deploy-playground ${{ vars.DOCKER_HUB_USERNAME }}/nextjs-deploy-playground:latest
